# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feed',
            new_name='Gallery',
        ),
    ]
